
DROP TABLE PAYMENT;
DROP TABLE RECOMMEND;
DROP TABLE REPORT;
DROP TABLE REVIEW;
DROP TABLE NONMEMBERINFO;
DROP TABLE RESERVATION;
DROP TABLE INSURANCE;
DROP TABLE RATING;
DROP TABLE VEHICLE;
DROP TABLE LOCATION;
DROP TABLE FUELTYPE;
DROP TABLE CARTYPE;
DROP TABLE COUPON;
DROP TABLE MEMBER_INFO;
DROP TABLE MEMBER;
DROP TABLE NOTICE;
DROP TABLE COUPON_MANAGE;
DROP TABLE INQUIRY;

CREATE TABLE INQUIRY (
       IDX NUMBER CONSTRAINT INQUIRY_IDX_PK PRIMARY KEY NOT NULL
     , TITLE VARCHAR2(100) NOT NULL 
     , CONTENT CLOB NOT NULL
);

DROP SEQUENCE INQUIRY_SEQ;
CREATE SEQUENCE INQUIRY_SEQ;

INSERT INTO INQUIRY VALUES(INQUIRY_SEQ.NEXTVAL, '자주 묻는 질문 제목 1', '자주 묻는 질문 내용 테스트 1');
INSERT INTO INQUIRY VALUES(INQUIRY_SEQ.NEXTVAL, '자주 묻는 질문 제목 2', '자주 묻는 질문 내용 테스트 2');
INSERT INTO INQUIRY VALUES(INQUIRY_SEQ.NEXTVAL, '자주 묻는 질문 제목 3', '자주 묻는 질문 내용 테스트 3');
INSERT INTO INQUIRY VALUES(INQUIRY_SEQ.NEXTVAL, '자주 묻는 질문 제목 4', '자주 묻는 질문 내용 테스트 4');
INSERT INTO INQUIRY VALUES(INQUIRY_SEQ.NEXTVAL, '자주 묻는 질문 제목 5', '자주 묻는 질문 내용 테스트 5');

SELECT * FROM INQUIRY;

CREATE TABLE COUPON_MANAGE (
       IDX NUMBER CONSTRAINT COUPON_MANAGE_IDX_PK PRIMARY KEY NOT NULL 
     , RATE NUMBER(5, 3) NOT NULL 
     , PERIOD NUMBER NOT NULL 
     , NAME VARCHAR2(30) NOT NULL
);

DROP SEQUENCE COUPON_MANAGE_SEQ;
CREATE SEQUENCE COUPON_MANAGE_SEQ;

INSERT INTO COUPON_MANAGE VALUES(0, 0, 0, '쿠폰 아님');
INSERT INTO COUPON_MANAGE VALUES(COUPON_MANAGE_SEQ.NEXTVAL, 0.20, 14, '쿠폰 테스트 2');
INSERT INTO COUPON_MANAGE VALUES(COUPON_MANAGE_SEQ.NEXTVAL, 0.10, 5, '쿠폰 테스트 3');
INSERT INTO COUPON_MANAGE VALUES(COUPON_MANAGE_SEQ.NEXTVAL, 0.30, 7, '쿠폰 테스트 4');
INSERT INTO COUPON_MANAGE VALUES(COUPON_MANAGE_SEQ.NEXTVAL, 0.05, 12, '쿠폰 테스트 5');

SELECT * FROM COUPON_MANAGE;

CREATE TABLE NOTICE (
       IDX NUMBER CONSTRAINT NOTICE_IDX_PK PRIMARY KEY NOT NULL 
     , TITLE VARCHAR2(100) NOT NULL 
     , CONTENT CLOB NOT NULL 
     , CREATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL
     , READ_COUNT NUMBER DEFAULT 0 NOT NULL
     , UPDATE_DATE DATE DEFAULT NULL
     , DELETE_DATE DATE DEFAULT NULL
);

DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ;

INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '공지사항 테스트 1', '공지사항 내용 테스트입니다 1', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '공지사항 테스트 2', '공지사항 내용 테스트입니다 2', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '공지사항 테스트 3', '공지사항 내용 테스트입니다 3', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '공지사항 테스트 4', '공지사항 내용 테스트입니다 4', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '공지사항 테스트 5', '공지사항 내용 테스트입니다 5', DEFAULT, DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM NOTICE;

CREATE TABLE MEMBER (
       IDX NUMBER CONSTRAINT MEMBER_IDX_PK PRIMARY KEY NOT NULL 
     , USERNAME VARCHAR2(20) NOT NULL 
     , PASSWORD VARCHAR2(100) NOT NULL 
     , ENABLED NUMBER DEFAULT 1 CONSTRAINT MEMBER_ENABLED_CK CHECK (ENABLED IN (0, 1)) NOT NULL
     , AUTH VARCHAR2(50) DEFAULT 'ROLE_USER' NOT NULL
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ;

INSERT INTO MEMBER VALUES(0, 'NONEMEMBER', 'NONEMEMBER', 0, DEFAULT);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'admin', '{noop}admin', DEFAULT, 'ROLE_ADMIN');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'manager', '{noop}manager', DEFAULT, 'ROLE_MANAGER');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user11', '{noop}user11', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user22', '{noop}user22', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user33', '{noop}user33', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user44', '{noop}user44', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user55', '{noop}user55', DEFAULT, DEFAULT);

SELECT * FROM MEMBER;

CREATE TABLE MEMBER_INFO (
       IDX NUMBER CONSTRAINT MEMBER_INFO_IDX_FK REFERENCES MEMBER(IDX) CONSTRAINT MEMBER_INFO_PK PRIMARY KEY NOT NULL
     , NAME VARCHAR2(30) NOT NULL 
     , GENDER NUMBER NOT NULL
     , BIRTH VARCHAR2(10) NOT NULL 
     , PHONE_NUMBER VARCHAR2(20)
     , LICENSE VARCHAR2(20) NOT NULL 
     , EMAIL VARCHAR2(50) NOT NULL
);

DROP SEQUENCE MEMBER_INFO_SEQ;
CREATE SEQUENCE MEMBER_INFO_SEQ;

INSERT INTO MEMBER_INFO VALUES(MEMBER_INFO_SEQ.NEXTVAL, '유저1', 0, '19930219', '01012345678', '111307273809', 'user11@test.or.kr');
INSERT INTO MEMBER_INFO VALUES(MEMBER_INFO_SEQ.NEXTVAL, '유저2', 1, '19880711', '01023435456', '171228374911', 'user22@test.or.kr');
INSERT INTO MEMBER_INFO VALUES(MEMBER_INFO_SEQ.NEXTVAL, '유저3', 0, '20001110', '01012477765', '222038927880', 'user33@test.or.kr');
INSERT INTO MEMBER_INFO VALUES(MEMBER_INFO_SEQ.NEXTVAL, '유저4', 1, '19771203', '01068644323', '131011234271', 'user44@test.or.kr');
INSERT INTO MEMBER_INFO VALUES(MEMBER_INFO_SEQ.NEXTVAL, '유저5', 0, '20010107', '01068992143', '282187263862', 'user55@test.or.kr');

SELECT * FROM MEMBER_INFO;

CREATE TABLE COUPON (
       IDX NUMBER CONSTRAINT COUPON_IDX_PK PRIMARY KEY NOT NULL 
     , START_DATE DATE DEFAULT SYSTIMESTAMP 
     , EXPIRE_DATE DATE DEFAULT NULL
     , COUPON_IDX NUMBER CONSTRAINT COUPON_IDX_FK REFERENCES COUPON_MANAGE(IDX) NOT NULL
     , MEMBER_IDX NUMBER CONSTRAINT COUPON_MEMBER_FK REFERENCES MEMBER(IDX) NOT NULL
);

DROP SEQUENCE COUPON_SEQ;
CREATE SEQUENCE COUPON_SEQ;

INSERT INTO COUPON VALUES(0, NULL, DEFAULT, 0, 0);
INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, DEFAULT, (SELECT (SYSTIMESTAMP + PERIOD) FROM COUPON_MANAGE WHERE IDX = 3), 3, 3);
INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, DEFAULT, (SELECT (SYSTIMESTAMP + PERIOD) FROM COUPON_MANAGE WHERE IDX = 2), 2, 3);
INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, DEFAULT, (SELECT (SYSTIMESTAMP + PERIOD) FROM COUPON_MANAGE WHERE IDX = 1), 1, 5);
INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, DEFAULT, (SELECT (SYSTIMESTAMP + PERIOD) FROM COUPON_MANAGE WHERE IDX = 4), 4, 6);
INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, DEFAULT, (SELECT (SYSTIMESTAMP + PERIOD) FROM COUPON_MANAGE WHERE IDX = 3), 3, 6);

SELECT * FROM COUPON;

CREATE TABLE CARTYPE (
       IDX NUMBER CONSTRAINT CARTYPE_IDX_PK PRIMARY KEY NOT NULL 
     , TYPE VARCHAR2(20) NOT NULL
);

DROP SEQUENCE CARTYPE_SEQ;
CREATE SEQUENCE CARTYPE_SEQ;

INSERT INTO CARTYPE VALUES(CARTYPE_SEQ.NEXTVAL, '휘발유');
INSERT INTO CARTYPE VALUES(CARTYPE_SEQ.NEXTVAL, '경유');
INSERT INTO CARTYPE VALUES(CARTYPE_SEQ.NEXTVAL, '전기');
INSERT INTO CARTYPE VALUES(CARTYPE_SEQ.NEXTVAL, '하이브리드');

SELECT * FROM CARTYPE;

CREATE TABLE FUELTYPE (
       IDX NUMBER CONSTRAINT FUELTYPE_IDX_PK PRIMARY KEY NOT NULL 
     , TYPE VARCHAR2(20) NOT NULL
);

DROP SEQUENCE FUELTYPE_SEQ;
CREATE SEQUENCE FUELTYPE_SEQ;

INSERT INTO FUELTYPE VALUES(FUELTYPE_SEQ.NEXTVAL, '소형');
INSERT INTO FUELTYPE VALUES(FUELTYPE_SEQ.NEXTVAL, '중형');
INSERT INTO FUELTYPE VALUES(FUELTYPE_SEQ.NEXTVAL, '대형');
INSERT INTO FUELTYPE VALUES(FUELTYPE_SEQ.NEXTVAL, 'SUV');
INSERT INTO FUELTYPE VALUES(FUELTYPE_SEQ.NEXTVAL, '수입');

SELECT * FROM FUELTYPE;

CREATE TABLE LOCATION (
       IDX NUMBER CONSTRAINT LOCATION_IDX_PK PRIMARY KEY NOT NULL 
     , NAME VARCHAR2 (30) NOT NULL 
     , LATITUDE NUMBER NOT NULL 
     , LONGITUDE NUMBER NOT NULL 
     , PHONE_NUMBER VARCHAR2(15) NOT NULL 
     , BUSINESS_HOURS VARCHAR2(15) NOT NULL 
     , ADDRESS VARCHAR2(100) NOT NULL
);

DROP SEQUENCE LOCATION_SEQ;
CREATE SEQUENCE LOCATION_SEQ;

INSERT INTO LOCATION VALUES(LOCATION_SEQ.NEXTVAL, '강남점', 37.49640072828634, 127.02725329040501, '02-1111-0111', '09:00-21:00', '서울 강남구 도산대로 336');
INSERT INTO LOCATION VALUES(LOCATION_SEQ.NEXTVAL, '용산점', 37.529538323634696, 126.96746826066268, '02-1234-5678', '09:00-21:00', '서울 용산구 한강로동 한강대로 95');
INSERT INTO LOCATION VALUES(LOCATION_SEQ.NEXTVAL, '수원점', 37.264552267986566, 126.99859642936599, '031-1010-2020', '09:00-18:00', '경기도 수원시 권선구 세화로 134');
INSERT INTO LOCATION VALUES(LOCATION_SEQ.NEXTVAL, '일산점', 37.66835722957077, 126.75113514893188, '031-8877-9888', '07:00-22:00', '경기도 고양시 일산서구 호수로 817');
INSERT INTO LOCATION VALUES(LOCATION_SEQ.NEXTVAL, '송도점', 37.395677541772194, 126.63883623016922, '032-2222-1234', '08:00-20:00', '인천광역시 연수구 인천 연수구 센트럴로 232');

SELECT * FROM LOCATION;

CREATE TABLE VEHICLE (
       IDX NUMBER CONSTRAINT VEHICLE_IDX_PK PRIMARY KEY NOT NULL 
     , MODEL VARCHAR2(50) NOT NULL 
     , YEAR NUMBER NOT NULL 
     , PRICE NUMBER NOT NULL 
     , IMAGE VARCHAR2(300) NOT NULL
     , MAKER VARCHAR2(20) NOT NULL 
     , LOCATION_IDX NUMBER CONSTRAINT VEHICLE_LOCATION_FK REFERENCES LOCATION(IDX) NOT NULL
     , FUELTYPE_IDX NUMBER CONSTRAINT VEHICLE_FUELTYPE_FK REFERENCES FUELTYPE(IDX) NOT NULL
     , CARTYPE_IDX NUMBER CONSTRAINT VEHICLE_CARTYPE_FK REFERENCES CARTYPE(IDX) NOT NULL
);

INSERT ALL
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(1, '쏘나타', 2, 25000, '쏘나타.jpg', '현대', 5, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(2, '아반떼', 4, 32000, '아반떼.jpg', '현대', 2, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(3, '레이', 10, 49000, '레이.jpg', '기아', 5, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(4, '쏘렌토', 4, 41000, '쏘렌토.jpg', '기아', 3, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(5, '싼타페', 8, 37000, '싼타페.jpg', '현대', 3, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(6, '코나', 6, 27000, '코나.jpg', '현대', 1, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(7, '모닝', 1, 11000, '모닝.jpg', '기아', 2, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(8, '레이', 8, 10000, '레이.jpg', '기아', 5, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(9, '티볼리', 9, 47000, '티볼리.jpg', '쌍용', 5, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(10, '토레스', 5, 21000, '토레스.jpg', '쌍용', 1, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(11, '쏘나타', 3, 32000, '쏘나타.jpg', '현대', 2, 4, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(12, '코나', 1, 43000, '코나.jpg', '현대', 5, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(13, '캐스퍼', 2, 44000, '캐스퍼.jpg', '현대', 3, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(14, '아반떼', 6, 41000, '아반떼.jpg', '현대', 5, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(15, '레이', 6, 15000, '레이.jpg', '기아', 1, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(16, '모닝', 2, 29000, '모닝.jpg', '기아', 5, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(17, '스팅어', 6, 11000, '스팅어.jpg', '기아', 4, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(18, '쏘렌토', 10, 31000, '쏘렌토.jpg', '기아', 5, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(19, '모하비', 5, 34000, '모하비.jpg', '기아', 2, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(20, 'QM6', 1, 49000, 'QM6.jpg', '르노', 2, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(21, 'SM7', 10, 27000, 'SM7.jpg', '르노', 2, 5, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(22, '스파크', 3, 27000, '스파크.jpg', '쉐보레', 4, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(23, '마티즈', 9, 43000, '마티즈.jpg', '쉐보레', 4, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(24, '트레일블레이저', 6, 32000, '트레일블레이저.jpg', '쉐보레', 1, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(25, '토레스', 1, 17000, '토레스.jpg', '쌍용', 4, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(26, '이쿼녹스', 4, 33000, '이쿼녹스.jpg', '쉐보레', 3, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(27, '볼트', 3, 28000, '볼트.jpg', '쉐보레', 4, 4, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(28, 'GV80', 5, 33000, 'GV80.jpg', '제네시스', 5, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(29, 'K8', 7, 39000, 'K8.jpg', '기아', 5, 4, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(30, 'K8', 6, 29000, 'K8.jpg', '기아', 2, 4, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(31, 'K5', 6, 14000, 'K5.jpg', '기아', 2, 4, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(32, '208 해치백', 5, 38000, '208 해치백.jpg', '푸조', 4, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(33, '3008', 4, 15000, '3008.jpg', '푸조', 1, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(34, '투아렉', 2, 40000, '투아렉.jpg', '폭스바겐', 4, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(35, 'A8', 5, 44000, 'A8.jpg', '아우디', 3, 1, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(36, 'Q2', 2, 46000, 'Q2.jpg', '아우디', 3, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(37, 'SQ5', 6, 31000, 'SQ5.jpg', '아우디', 4, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(38, 'G80 스포츠', 7, 48000, 'G80 스포츠.jpg', '제네시스', 3, 1, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(39, '일렉트리파이드', 6, 47000, '일렉트리파이드.jpg', '제네시스', 5, 3, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(40, '쏘나타', 5, 15000, '쏘나타.jpg', '현대', 3, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(41, '그랜저', 7, 49000, '그랜저.jpg', '현대', 3, 5, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(42, '아이오닉', 5, 13000, '아이오닉.jpg', '현대', 2, 3, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(43, '니로', 2, 46000, '니로.jpg', '기아', 4, 4, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(44, '쏘나타', 10, 17000, '쏘나타.jpg', '현대', 3, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(45, '쏘나타', 3, 33000, '쏘나타.jpg', '현대', 3, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(46, '쏘나타', 10, 45000, '쏘나타.jpg', '현대', 5, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(47, '아반떼', 2, 45000, '아반떼.jpg', '현대', 3, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(48, '아반떼', 5, 16000, '아반떼.jpg', '현대', 4, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(49, '모닝', 8, 12000, '모닝.jpg', '기아', 3, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(50, '레이', 1, 13000, '레이.jpg', '기아', 5, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(51, '브롱코 스포츠', 6, 37000, '브롱코 스포츠.jpg', '포드', 2, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(52, '머스탱 쿠페', 4, 41000, '머스탱 쿠페.jpg', '포드', 3, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(53, 'Q2', 10, 43000, 'Q2.jpg', '아우디', 3, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(54, 'SQ5', 5, 48000, 'SQ5.jpg', '아우디', 2, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(55, '208 해치백', 9, 36000, '208 해치백.jpg', '푸조', 2, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(56, 'i7', 4, 49000, 'i7.jpg', 'BMW', 2, 3, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(57, 'i7', 4, 15000, 'i7.jpg', 'BMW', 3, 3, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(58, 'i3', 6, 14000, 'i3.jpg', 'BMW', 1, 3, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(59, 'i3', 8, 11000, 'i3.jpg', 'BMW', 2, 3, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(60, 'EQS SUV', 10, 21000, 'EQS SUV.jpg', '벤츠', 2, 3, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(61, 'A클래스(3세대)', 10, 41000, 'A클래스(3세대).jpg', '벤츠', 2, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(62, 'A클래스(3세대)', 8, 17000, 'A클래스(3세대).jpg', '벤츠', 5, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(63, 'A클래스(3세대)', 8, 23000, 'A클래스(3세대).jpg', '벤츠', 4, 2, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(64, 'GLC클래스 쿠페', 2, 16000, 'GLC클래스 쿠페.jpg', '벤츠', 2, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(65, '코나', 2, 18000, '코나.jpg', '현대', 4, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(66, '모닝', 1, 43000, '모닝.jpg', '기아', 4, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(67, '레이', 8, 35000, '레이.jpg', '기아', 1, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(68, '스팅어', 8, 32000, '스팅어.jpg', '기아', 1, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(69, '쏘렌토', 5, 16000, '쏘렌토.jpg', '기아', 4, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(70, '싼타페', 3, 44000, '싼타페.jpg', '현대', 4, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(71, '스타리아', 10, 21000, '스타리아.jpg', '현대', 1, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(72, '포레스트', 7, 42000, '포레스트.jpg', '현대', 5, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(73, '쏘나타', 4, 18000, '쏘나타.jpg', '현대', 4, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(74, '코나', 4, 20000, '코나.jpg', '현대', 4, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(75, '레이', 6, 38000, '레이.jpg', '기아', 2, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(76, '모닝', 3, 30000, '모닝.jpg', '기아', 5, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(77, '마티즈', 10, 22000, '마티즈.jpg', '쉐보레', 1, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(78, '스파크', 6, 44000, '스파크.jpg', '쉐보레', 4, 1, 1)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(79, '임팔라', 10, 47000, '임팔라.jpg', '쉐보레', 4, 1, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(80, '볼트', 7, 38000, '볼트.jpg', '쉐보레', 2, 4, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(81, 'GV80', 10, 11000, 'GV80.jpg', '제네시스', 5, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(82, 'G90 LWB', 3, 42000, 'G90 LWB.jpg', '제네시스', 2, 1, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(83, 'G70', 3, 22000, 'G70.jpg', '제네시스', 3, 2, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(84, 'GV60', 9, 16000, 'GV60.jpg', '제네시스', 3, 3, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(85, 'G70 슈팅브레이크', 4, 37000, 'G70 슈팅브레이크.jpg', '제네시스', 3, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(86, '일렉트리파이드', 8, 49000, '일렉트리파이드.jpg', '제네시스', 4, 3, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(87, 'EQ900', 5, 39000, 'EQ900.jpg', '제네시스', 2, 1, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(88, '셀토스', 5, 46000, '셀토스.jpg', '기아', 2, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(89, '모하비', 9, 27000, '모하비.jpg', '기아', 5, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(90, '카니발', 1, 19000, '카니발.jpg', '기아', 1, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(91, 'EV9', 2, 49000, 'EV9.jpg', '기아', 4, 3, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(92, '스포티지', 3, 47000, '스포티지.jpg', '기아', 5, 4, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(93, '그랜저 하이브리드', 7, 24000, '그랜저 하이브리드.jpg', '현대', 4, 4, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(94, '그랜저', 5, 14000, '그랜저.jpg', '현대', 1, 5, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(95, '스타리아', 5, 13000, '스타리아.jpg', '현대', 1, 2, 4)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(96, '코나', 4, 24000, '코나.jpg', '현대', 2, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(97, '아반떼', 7, 13000, '아반떼.jpg', '현대', 5, 1, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(98, '쏘나타', 3, 35000, '쏘나타.jpg', '현대', 3, 5, 3)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(99, '티볼리', 7, 37000, '티볼리.jpg', '쌍용', 5, 1, 2)
INTO VEHICLE(IDX, MODEL, YEAR, PRICE, IMAGE, MAKER, LOCATION_IDX, FUELTYPE_IDX, CARTYPE_IDX)  VALUES(100, '토레스', 8, 31000, '토레스.jpg', '쌍용', 2, 1, 3)
SELECT * FROM DUAL;

SELECT * FROM VEHICLE;

CREATE TABLE RATING (
       RATING_AVG NUMBER(5, 3) NOT NULL 
     , VEHICLE_IDX NUMBER CONSTRAINT RATING_VEHICLE_FK REFERENCES VEHICLE(IDX) NOT NULL 
);

INSERT INTO RATING VALUES(3.7, 4);
INSERT INTO RATING VALUES(2.5, 1);
INSERT INTO RATING VALUES(4.9, 2);
INSERT INTO RATING VALUES(3.3, 3);
INSERT INTO RATING VALUES(1.1, 5);

SELECT * FROM RATING;

CREATE TABLE INSURANCE (
       IDX NUMBER CONSTRAINT INSURANCE_IDX_PK PRIMARY KEY NOT NULL 
     , NAME VARCHAR2(30) NOT NULL 
     , PRICE NUMBER(5, 3) NOT NULL
);

DROP SEQUENCE INSURANCE_SEQ;
CREATE SEQUENCE INSURANCE_SEQ;

INSERT INTO INSURANCE VALUES(INSURANCE_SEQ.NEXTVAL, '미가입', 0);
INSERT INTO INSURANCE VALUES(INSURANCE_SEQ.NEXTVAL, '일반', 0.1);
INSERT INTO INSURANCE VALUES(INSURANCE_SEQ.NEXTVAL, '완전', 0.15);
INSERT INTO INSURANCE VALUES(INSURANCE_SEQ.NEXTVAL, '슈퍼', 0.2);

SELECT * FROM INSURANCE;

CREATE TABLE RESERVATION (
       IDX NUMBER CONSTRAINT RESERVATION_IDX_PK PRIMARY KEY NOT NULL 
     , RESERV_START DATE DEFAULT SYSTIMESTAMP NOT NULL
     , RESERV_END DATE NOT NULL
     , RESERV_STATE NUMBER DEFAULT 1 CONSTRAINT RESERVATION_STATE_CK CHECK(RESERV_STATE IN (0, 1, 2)) NOT NULL
     , IS_MEMBER NUMBER DEFAULT 1 CONSTRAINT RESERVATION_IS_MEMBER_CK CHECK(IS_MEMBER IN (0, 1)) NOT NULL
     , INSURANCE_IDX NUMBER CONSTRAINT RESERVATION_INSURANCE_FK REFERENCES INSURANCE(IDX) NOT NULL
     , VEHICLE_IDX NUMBER CONSTRAINT RESERVATION_VEHICLE_FK REFERENCES VEHICLE(IDX) NOT NULL 
     , MEMBER_IDX NUMBER CONSTRAINT RESERVATION_MEMBER_FK REFERENCES MEMBER(IDX)
     , RENT_LOCATION NUMBER CONSTRAINT RESERVATION_RENT_LOCATION_FK REFERENCES LOCATION(IDX) NOT NULL
     , RETURN_LOCATION NUMBER CONSTRAINT RESERVATION_RETURN_LOCATION_FK REFERENCES LOCATION(IDX) NOT NULL
     , COUPON_IDX NUMBER CONSTRAINT RESERVATION_COUPON_FK REFERENCES COUPON(IDX)
);

DROP SEQUENCE RESERVATION_SEQ;
CREATE SEQUENCE RESERVATION_SEQ;

INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL, DEFAULT, SYSTIMESTAMP + 10, DEFAULT, DEFAULT, 1, 1, 3, 2, 1, 1);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL, DEFAULT, SYSTIMESTAMP + 14, DEFAULT, 0, 2, 2, 0, 1, 1, 2);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL, DEFAULT, SYSTIMESTAMP + 12, DEFAULT, 0, 4, 3, 0, 1, 3, 3);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL, DEFAULT, SYSTIMESTAMP + 20, DEFAULT, DEFAULT, 3, 4, 5, 4, 4, 4);
INSERT INTO RESERVATION VALUES(RESERVATION_SEQ.NEXTVAL, DEFAULT, SYSTIMESTAMP + 21, DEFAULT, DEFAULT, 1, 5, 6, 5, 5, 5);

SELECT * FROM RESERVATION;

CREATE TABLE NONMEMBERINFO (
       IDX CONSTRAINT NONMEMBERINFO_FK REFERENCES RESERVATION(IDX) CONSTRAINT NONMEMBERINFO_PK PRIMARY KEY
     , NAME VARCHAR2(30) NOT NULL
     , BIRTH VARCHAR2(10) NOT NULL
     , PHONE_NUMBER VARCHAR2(20) NOT NULL
     , EMAIL VARCHAR2(50) NOT NULL
     , LICENSE VARCHAR2(20) NOT NULL
);

INSERT INTO NONMEMBERINFO VALUES(2, '가나다', '19970820', '01093827372', 'abc@test.or.kr', '122029373301');
INSERT INTO NONMEMBERINFO VALUES(3, '라마바', '19941010', '01022739923', 'def@test.or.kr', '201499382712');

SELECT * FROM NONMEMBERINFO;

CREATE TABLE REVIEW (
       IDX NUMBER CONSTRAINT REVIEW_IDX_PK PRIMARY KEY NOT NULL 
     , CONTENT VARCHAR2(300) NOT NULL 
     , CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL 
     , RECOMMEND NUMBER DEFAULT 0 NOT NULL 
     , SCORE NUMBER(2, 1) NOT NULL 
     , VEHICLE_IDX NUMBER CONSTRAINT REVIEW_VEHICLE_FK REFERENCES VEHICLE(IDX) NOT NULL
);

DROP SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REVIEW_SEQ;

INSERT INTO REVIEW VALUES(REVIEW_SEQ.NEXTVAL, '리뷰 테스트입니다 1', DEFAULT, DEFAULT, 3.5, 1);
INSERT INTO REVIEW VALUES(REVIEW_SEQ.NEXTVAL, '리뷰 테스트입니다 2', DEFAULT, DEFAULT, 4.5, 3);
INSERT INTO REVIEW VALUES(REVIEW_SEQ.NEXTVAL, '리뷰 테스트입니다 3', DEFAULT, DEFAULT, 2.5, 4);
INSERT INTO REVIEW VALUES(REVIEW_SEQ.NEXTVAL, '리뷰 테스트입니다 4', DEFAULT, DEFAULT, 4.0, 3);
INSERT INTO REVIEW VALUES(REVIEW_SEQ.NEXTVAL, '리뷰 테스트입니다 5', DEFAULT, DEFAULT, 5.0, 2);

SELECT * FROM REVIEW;

CREATE TABLE REPORT (
       REVIEW_IDX NUMBER CONSTRAINT REPORT_REVIEW_FK REFERENCES REVIEW(IDX) NOT NULL 
     , MEMBER_IDX NUMBER CONSTRAINT REPORT_MEMBER_FK REFERENCES MEMBER(IDX) NOT NULL
     , CONSTRAINT REPORT_PK PRIMARY KEY(REVIEW_IDX, MEMBER_IDX)
);

INSERT INTO REPORT VALUES(3, 3);
INSERT INTO REPORT VALUES(2, 5);
INSERT INTO REPORT VALUES(4, 6);
INSERT INTO REPORT VALUES(3, 5);
INSERT INTO REPORT VALUES(1, 4);

SELECT * FROM REPORT;

CREATE TABLE RECOMMEND (
       REVIEW_IDX NUMBER CONSTRAINT RECOMMEND_REVIEW_FK REFERENCES REVIEW(IDX) NOT NULL 
     , MEMBER_IDX NUMBER CONSTRAINT RECOMMEND_MEMBER_FK REFERENCES MEMBER(IDX) NOT NULL
     , CONSTRAINT RECOMMEND_PK PRIMARY KEY(REVIEW_IDX, MEMBER_IDX)
);

INSERT INTO RECOMMEND VALUES(1, 3);
INSERT INTO RECOMMEND VALUES(3, 3);
INSERT INTO RECOMMEND VALUES(4, 5);
INSERT INTO RECOMMEND VALUES(2, 5);
INSERT INTO RECOMMEND VALUES(3, 4);

SELECT * FROM RECOMMEND;

CREATE TABLE PAYMENT (
       PAY_CODE NUMBER CONSTRAINT PAYMENT_IDX_PK PRIMARY KEY NOT NULL 
     , PAY_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL 
     , PAY_METHOD VARCHAR2(15) NOT NULL 
     , RESERV_IDX NUMBER CONSTRAINT PAYMENT_RESERVATION_FK REFERENCES RESERVATION(IDX) NOT NULL 
     , RESERV_CANCEL NUMBER DEFAULT 0 CONSTRAINT PAYMENT_RESERV_CANCEL_CK CHECK(RESERV_CANCEL IN(0, 1)) NOT NULL
     , CANCEL_DATE DATE DEFAULT NULL
     , PRICE NUMBER NOT NULL
);
DROP SEQUENCE PAYMENT_SEQ;
CREATE SEQUENCE PAYMENT_SEQ;

INSERT INTO PAYMENT VALUES(PAYMENT_SEQ.NEXTVAL, DEFAULT, '신용카드', 1, DEFAULT, DEFAULT, 50000);
INSERT INTO PAYMENT VALUES(PAYMENT_SEQ.NEXTVAL, DEFAULT, '계좌이체', 2, DEFAULT, DEFAULT, 50000);
INSERT INTO PAYMENT VALUES(PAYMENT_SEQ.NEXTVAL, DEFAULT, '신용카드', 3, DEFAULT, DEFAULT, 50000);
INSERT INTO PAYMENT VALUES(PAYMENT_SEQ.NEXTVAL, DEFAULT, '신용카드', 4, DEFAULT, DEFAULT, 50000);
INSERT INTO PAYMENT VALUES(PAYMENT_SEQ.NEXTVAL, DEFAULT, '신용카드', 5, DEFAULT, DEFAULT, 50000);

SELECT * FROM PAYMENT;

COMMIT;