DROP TABLE IF EXISTS `REPORT`;

CREATE TABLE `REPORT` (
	`IDX`	NUMBER	NOT NULL,
	`REVIEW_IDX`	NUMBER	NOT NULL,
	`MEMBER_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `VEHICLE`;

CREATE TABLE `VEHICLE` (
	`IDX`	NUMBER	NOT NULL,
	`MODEL`	VARCHAR2(50)	NOT NULL,
	`YEAR`	NUMBER	NOT NULL,
	`PRICE`	NUMBER	NOT NULL,
	`IMAGE`	VARCHAR2(300)	NOT NULL,
	`LOCATION_IDX`	NUMBER	NOT NULL,
	`MAKER`	VARCHAR2(20)	NOT NULL,
	`FUELTYPE_IDX`	NUMBER	NOT NULL,
	`CARTYPE_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `RATING`;

CREATE TABLE `RATING` (
	`RATING_AVG`	NUMBER	NOT NULL,
	`VEHICLE_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `CARTYPE`;

CREATE TABLE `CARTYPE` (
	`IDX`	NUMBER	NOT NULL,
	`TYPE`	NUMBER	NOT NULL	COMMENT '전기(0) /경형(1) / 준중형(2) / 중형(3) /대형(4)'
);

DROP TABLE IF EXISTS `LOCATION`;

CREATE TABLE `LOCATION` (
	`IDX`	NUMBER	NOT NULL,
	`NAME`	VARCHAR2 (30)	NOT NULL,
	`LATITUDE`	NUMBER	NOT NULL,
	`LONGITUDE`	NUMBER	NOT NULL,
	`PHONE_NUMBER`	VARCHAR2(15)	NOT NULL,
	`BUSINESS_HOURS`	VARCHAR2(15)	NOT NULL,
	`ADDRESS`	VARCHAR2(100)	NOT NULL
);

DROP TABLE IF EXISTS `RESERVATION`;

CREATE TABLE `RESERVATION` (
	`IDX`	NUMBER	NOT NULL,
	`RESERV_START`	DATE	NOT NULL	DEFAULT SYSTIMESTAMP,
	`RESERV_END`	DATE	NOT NULL	COMMENT '시작 날짜 + 예약 기간 합쳐서 기본값',
	`RESERV_STATE`	NUMBER	NOT NULL	DEFAULT 1	COMMENT '대여종료(0) / 대여중(1)',
	`IS_MEMBER`	NUMBER	NOT NULL	DEFAULT 1	COMMENT '미가입(0) / 가입(1)',
	`INSURANCE_IDX`	NUMBER	NULL,
	`VEHICLE_IDX`	NUMBER	NOT NULL,
	`MEMBER_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `REVIEW`;

CREATE TABLE `REVIEW` (
	`IDX`	NUMBER	NOT NULL,
	`CONTENT`	VARCHAR2(300)	NOT NULL,
	`DATE`	DATE	NOT NULL,
	`LIKE`	NUMBER	NOT NULL,
	`SCORE`	NUMBER	NOT NULL,
	`VEHICLE_IDX`	NUMBER	NOT NULL	COMMENT 'ON DELETE CASCADE'
);

DROP TABLE IF EXISTS `COUPON`;

CREATE TABLE `COUPON` (
	`IDX`	NUMBER	NOT NULL,
	`START_DATE`	DATE	NOT NULL,
	`EXPIRE_DATE`	DATE	NOT NULL,
	`COUPON_IDX`	NUMBER	NOT NULL,
	`MEMBER_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `INQUIRY`;

CREATE TABLE `INQUIRY` (
	`IDX`	NUMBER	NOT NULL,
	`TITLE`	VARCHAR2(100)	NOT NULL,
	`CONTENT`	CLOB	NOT NULL
);

DROP TABLE IF EXISTS `RECOMMEND`;

CREATE TABLE `RECOMMEND` (
	`IDX`	NUMBER	NOT NULL,
	`REVIEW_IDX`	NUMBER	NOT NULL,
	`MEMBER_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `COUPON_MANAGE`;

CREATE TABLE `COUPON_MANAGE` (
	`IDX`	NUMBER	NOT NULL,
	`RATE`	NUMBER	NOT NULL,
	`PEROID`	NUMBER	NOT NULL,
	`NAME`	VARCHAR2(30)	NOT NULL
);

DROP TABLE IF EXISTS `NOTICE`;

CREATE TABLE `NOTICE` (
	`IDX`	NUMBER	NOT NULL,
	`TITLE`	VARCHAR2(100)	NOT NULL,
	`CONTENT`	CLOB	NOT NULL,
	`CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSTIMESTAMP,
	`READ_COUNT`	NUMBER	NOT NULL	DEFAULT 0,
	`UPDATE_DATE`	DATE	NOT NULL,
	`DELETE_DATE`	DATE	NOT NULL
);

DROP TABLE IF EXISTS `PAYMENT`;

CREATE TABLE `PAYMENT` (
	`PAY_CODE`	NUMBER	NOT NULL,
	`PAY_DATE`	DATE	NOT NULL	DEFAULT SYSTIMESTAMP,
	`PAY_METHOD`	VARCHAR2(15)	NOT NULL,
	`RES_CODE`	NUMBER	NOT NULL,
	`RES_CANCLE`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '결제완료(0), 취소(1)',
	`CANCEL_DATE`	DATE	NULL	DEFAULT NULL
);

DROP TABLE IF EXISTS `INSURANCE`;

CREATE TABLE `INSURANCE` (
	`IDX`	NUMBER	NOT NULL,
	`NAME`	VARCHAR2(30)	NOT NULL,
	`PRICE`	NUMBER	NOT NULL,
	`RES_IDX`	NUMBER	NOT NULL
);

DROP TABLE IF EXISTS `FUELTYPE`;

CREATE TABLE `FUELTYPE` (
	`IDX`	NUMBER	NOT NULL,
	`TYPE`	VARCHAR2(20)	NULL
);

DROP TABLE IF EXISTS `MEBER_TEMP`;

CREATE TABLE `MEBER_TEMP` (
	`IDX`	NUMBER	NOT NULL,
	`USERNAME`	VARCHAR2(20)	NOT NULL,
	`PASSWORD`	VARCHAR2(30)	NOT NULL,
	`ENABLED`	NUMBER	NOT NULL	DEFAULT 1	COMMENT '0(비활성화) / 1(활성화)',
	`AUTH`	VARCHAR2(50)	NOT NULL	DEFAULT ROLE_USER
);

DROP TABLE IF EXISTS `MEMBER_INFO`;

CREATE TABLE `MEMBER_INFO` (
	`IDX`	NUMBER	NOT NULL,
	`NAME`	VARCHAR2(30)	NOT NULL,
	`GENDER`	NUMBER	NOT NULL	COMMENT '남자(0) / 여자(1)',
	`BIRTH`	VARCHAR2(10)	NOT NULL,
	`PHONE_NUMBER`	VARCHAR2(20)	NOT NULL,
	`LICENSE`	VARCHAR2(20)	NOT NULL,
	`EMAIL`	VARCHAR2(50)	NOT NULL
);

ALTER TABLE `REPORT` ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `VEHICLE` ADD CONSTRAINT `PK_VEHICLE` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `CARTYPE` ADD CONSTRAINT `PK_CARTYPE` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `LOCATION` ADD CONSTRAINT `PK_LOCATION` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `PK_RESERVATION` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `COUPON` ADD CONSTRAINT `PK_COUPON` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `INQUIRY` ADD CONSTRAINT `PK_INQUIRY` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `RECOMMEND` ADD CONSTRAINT `PK_RECOMMEND` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `COUPON_MANAGE` ADD CONSTRAINT `PK_COUPON_MANAGE` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `PK_PAYMENT` PRIMARY KEY (
	`PAY_CODE`
);

ALTER TABLE `INSURANCE` ADD CONSTRAINT `PK_INSURANCE` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `FUELTYPE` ADD CONSTRAINT `PK_FUELTYPE` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `MEBER_TEMP` ADD CONSTRAINT `PK_MEBER_TEMP` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `MEMBER_INFO` ADD CONSTRAINT `PK_MEMBER_INFO` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `FK_MEBER_TEMP_TO_REPORT_1` FOREIGN KEY (
	`MEMBER_IDX`
)
REFERENCES `MEBER_TEMP` (
	`IDX`
);

ALTER TABLE `VEHICLE` ADD CONSTRAINT `FK_LOCATION_TO_VEHICLE_1` FOREIGN KEY (
	`LOCATION_IDX`
)
REFERENCES `LOCATION` (
	`IDX`
);

ALTER TABLE `VEHICLE` ADD CONSTRAINT `FK_FUELTYPE_TO_VEHICLE_1` FOREIGN KEY (
	`FUELTYPE_IDX`
)
REFERENCES `FUELTYPE` (
	`IDX`
);

ALTER TABLE `VEHICLE` ADD CONSTRAINT `FK_CARTYPE_TO_VEHICLE_1` FOREIGN KEY (
	`CARTYPE_IDX`
)
REFERENCES `CARTYPE` (
	`IDX`
);

ALTER TABLE `RATING` ADD CONSTRAINT `FK_VEHICLE_TO_RATING_1` FOREIGN KEY (
	`VEHICLE_IDX`
)
REFERENCES `VEHICLE` (
	`IDX`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_INSURANCE_TO_RESERVATION_1` FOREIGN KEY (
	`INSURANCE_IDX`
)
REFERENCES `INSURANCE` (
	`IDX`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_VEHICLE_TO_RESERVATION_1` FOREIGN KEY (
	`VEHICLE_IDX`
)
REFERENCES `VEHICLE` (
	`IDX`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_MEBER_TEMP_TO_RESERVATION_1` FOREIGN KEY (
	`MEMBER_IDX`
)
REFERENCES `MEBER_TEMP` (
	`IDX`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_VEHICLE_TO_REVIEW_1` FOREIGN KEY (
	`VEHICLE_IDX`
)
REFERENCES `VEHICLE` (
	`IDX`
);

ALTER TABLE `COUPON` ADD CONSTRAINT `FK_COUPON_MANAGE_TO_COUPON_1` FOREIGN KEY (
	`COUPON_IDX`
)
REFERENCES `COUPON_MANAGE` (
	`IDX`
);

ALTER TABLE `COUPON` ADD CONSTRAINT `FK_MEBER_TEMP_TO_COUPON_1` FOREIGN KEY (
	`MEMBER_IDX`
)
REFERENCES `MEBER_TEMP` (
	`IDX`
);

ALTER TABLE `RECOMMEND` ADD CONSTRAINT `FK_REVIEW_TO_RECOMMEND_1` FOREIGN KEY (
	`REVIEW_IDX`
)
REFERENCES `REVIEW` (
	`IDX`
);

ALTER TABLE `RECOMMEND` ADD CONSTRAINT `FK_MEBER_TEMP_TO_RECOMMEND_1` FOREIGN KEY (
	`MEMBER_IDX`
)
REFERENCES `MEBER_TEMP` (
	`IDX`
);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `FK_RESERVATION_TO_PAYMENT_1` FOREIGN KEY (
	`RES_CODE`
)
REFERENCES `RESERVATION` (
	`IDX`
);

ALTER TABLE `INSURANCE` ADD CONSTRAINT `FK_RESERVATION_TO_INSURANCE_1` FOREIGN KEY (
	`RES_IDX`
)
REFERENCES `RESERVATION` (
	`IDX`
);

ALTER TABLE `MEMBER_INFO` ADD CONSTRAINT `FK_MEBER_TEMP_TO_MEMBER_INFO_1` FOREIGN KEY (
	`IDX`
)
REFERENCES `MEBER_TEMP` (
	`IDX`
);

