INSERT INTO PAYMENT VALUES(2, TO_DATE('230313'), '현금', DEFAULT, DEFAULT);
SELECT * FROM PAYMENT;

SELECT TO_NUMBER(EXTRACT(DAY FROM (SYSTIMESTAMP - PAY_DATE))) * 24 + TO_NUMBER(EXTRACT(HOUR FROM (SYSTIMESTAMP - PAY_DATE))) FROM PAYMENT WHERE PAY_CODE = 2;